FROM jupyter/scipy-notebook:latest

USER root
RUN apt-get update
RUN apt-get install -y python3-dev libpq-dev

# Install
RUN pip install --upgrade pip \
  && pip install ipython-sql \
  && pip install psycopg2 \
  && pip install sqlalchemy

CMD jupyter notebook --allow-root --NotebookApp.token="$NOTEBOOK_PASSWORD" /opt/analysis
